provider:
  name: faas
  gateway: https://faas.srv.locational.io
functions:
  fn-raster-vector-summary-stats-enhanced:
    handler: ./fn-raster-vector-summary-stats
    lang: dockerfile
    image: locational/fn-raster-vector-summary-stats-enhanced:0.2.1
    environment:
#      write_debug: true
      write_timeout: 60
      read_timeout: 60
      combine_output: false
