provider:
  name: faas
  gateway: https://faas.srv2.disarm.io
functions:
  fn-raster-vector-summary-stats-enhanced:
    lang: python-geospatial
    handler: ./fn-raster-vector-summary-stats-enhanced
    image: disarm/fn-raster-vector-summary-stats-enhanced
    environment:
      exec_timeout: 1020
      write_timeout: 1000
      read_timeout: 1000
      combine_output: false