provider:
  name: faas
  gateway: https://faas.srv2.disarm.io
functions:
  fn-raster-vector-summary-stats-enhanced:
    lang: python-geospatial
    handler: ./function
    image: disarm/fn-raster-vector-summary-stats-enhanced:1.0.0
    environment:
      combine_output: false